# Generated by Django 5.0.6 on 2024-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fopearation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileoperation',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
